CREATE TABLE USERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(45) CHECK (ROLE IN ('ADMIN', 'CLIENT', 'DEALER')) NOT NULL,
    STATUS VARCHAR(25) CHECK (STATUS IN ('ACTIVE', 'INACTIVE')) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

CREATE TABLE PRODUCTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    STATUS VARCHAR(25) CHECK (STATUS IN ('ACTIVE', 'INACTIVE')) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    USER_ID BIGINT,
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);


INSERT INTO USERS(USERNAME, EMAIL, PASSWORD, ROLE, STATUS)
VALUES('testAdmin_1',
'testAdmin_1@admin.com',
'$2a$10$2.Z9KhuJzzaEmF0wUv.s1.EFRv6QMIB5aiOjqXCx6bPP7JNpWDMCy',
'ADMIN',
'ACTIVE');
